export type TerminalAgentId = string;

export function renderShellIntegration(
  selected: TerminalAgentId[],
  executables: Partial<Record<TerminalAgentId, string>>,
  dataRoot?: string,
): string {
  const lines = [
    "# Generated by Memora Local. Re-run onboarding to update.",
    "# Each function preserves the original agent executable and captures its execution automatically.",
  ];
  for (const id of selected) {
    const executable = executables[id];
    if (!executable) continue;
    const environment = dataRoot ? `MEMORA_LOCAL_DATA_DIR=${JSON.stringify(dataRoot)} ` : "";
    lines.push(`${id}() { ${environment}command memora local run -- ${JSON.stringify(executable)} "$@"; }`);
  }
  return `${lines.join("\n")}\n`;
}

export function renderZshSourceLine(path: string): string {
  return `[ -f ${JSON.stringify(path)} ] && source ${JSON.stringify(path)}`;
}
